import { DEMO_CREDENTIALS } from "@/lib/auth";
import type {
  ActivityEvent,
  DemoUser,
  EvidenceDocument,
  Product,
  SupplyChainNode,
} from "@/lib/types";

/**
 * Offline snapshot of the Supabase catalog.
 *
 * Supabase is the source of truth (see `lib/data/catalog.ts`); this mirror is
 * only served when the database is unreachable, so a page render is never
 * blocked on the network. Keep it in sync with `supabase/migrations`.
 */

export const DEMO_USER: DemoUser = {
  id: "usr_maya",
  name: "Maya Chen",
  email: DEMO_CREDENTIALS.email,
  role: "Compliance Lead",
  initials: "MC",
};

export const asterChain: SupplyChainNode[] = [
  {
    id: "raw",
    stage: "Raw material",
    company: "Fina Fiber Co.",
    location: "İzmir, Türkiye",
    documents: 3,
    status: "Verified",
    note: "Recycled polyester source verified",
  },
  {
    id: "yarn",
    stage: "Yarn supplier",
    company: "Luma Spinning",
    location: "Gaziantep, Türkiye",
    documents: 2,
    status: "Verified",
    note: "GRS transaction certificate matched",
  },
  {
    id: "fabric",
    stage: "Fabric mill",
    company: "NovaTex Mill",
    location: "Prato, Italy",
    documents: 4,
    status: "Verified",
    note: "Composition and weight confirmed",
  },
  {
    id: "dye",
    stage: "Dyeing & finishing",
    company: "Chromia Works",
    location: "Como, Italy",
    documents: 1,
    status: "Missing",
    note: "Dye-lot REACH declaration requested",
  },
  {
    id: "assembly",
    stage: "Final assembly",
    company: "Atelier Miro",
    location: "Porto, Portugal",
    documents: 3,
    status: "In review",
    note: "Factory declaration awaiting approval",
  },
  {
    id: "packaging",
    stage: "Packaging",
    company: "Packwise Europe",
    location: "Rotterdam, Netherlands",
    documents: 2,
    status: "Verified",
    note: "FSC packaging evidence linked",
  },
];

const compactChain = (company: string, country: string): SupplyChainNode[] => [
  {
    id: `${company}-raw`,
    stage: "Raw material",
    company: `${company} Materials`,
    location: country,
    documents: 2,
    status: "Verified",
    note: "Source declaration linked",
  },
  {
    id: `${company}-fabric`,
    stage: "Fabric mill",
    company: `${company} Textiles`,
    location: country,
    documents: 3,
    status: "Verified",
    note: "Composition evidence linked",
  },
  {
    id: `${company}-assembly`,
    stage: "Final assembly",
    company: `${company} Manufacturing`,
    location: country,
    documents: 2,
    status: "In review",
    note: "Final declaration in review",
  },
];

export const products: Product[] = [
  {
    id: "OR-24017",
    name: "Aster Loop Jacket",
    sku: "AS-LJ-042-NVY",
    category: "Outerwear",
    season: "AW 2026",
    color: "Midnight navy",
    completion: 84,
    status: "Needs evidence",
    suppliers: 6,
    evidence: 15,
    openItems: 3,
    nextAction: "Collect dye-lot REACH declaration",
    owner: "Maya Chen",
    updatedAt: "12 min ago",
    material: "72% recycled polyester, 28% organic cotton",
    recycledContent: 72,
    chain: asterChain,
  },
  {
    id: "OR-24018",
    name: "Coastline Overshirt",
    sku: "CO-OS-118-SND",
    category: "Shirts",
    season: "SS 2027",
    color: "Washed sand",
    completion: 96,
    status: "In review",
    suppliers: 4,
    evidence: 11,
    openItems: 1,
    nextAction: "Approve factory conformity statement",
    owner: "Noah Williams",
    updatedAt: "1 hr ago",
    material: "100% organic cotton",
    recycledContent: 0,
    chain: compactChain("Alba", "Portugal"),
  },
  {
    id: "OR-24019",
    name: "Meridian Knit",
    sku: "ME-KN-220-CRM",
    category: "Knitwear",
    season: "AW 2026",
    color: "Soft cream",
    completion: 100,
    status: "Passport ready",
    suppliers: 5,
    evidence: 18,
    openItems: 0,
    nextAction: "Publish product passport",
    owner: "Maya Chen",
    updatedAt: "Yesterday",
    material: "80% RWS wool, 20% recycled nylon",
    recycledContent: 20,
    chain: compactChain("Merino", "Italy"),
  },
  {
    id: "OR-24020",
    name: "Forma Tailored Trouser",
    sku: "FO-TR-305-BLK",
    category: "Bottoms",
    season: "Core",
    color: "Graphite black",
    completion: 71,
    status: "At risk",
    suppliers: 7,
    evidence: 9,
    openItems: 6,
    nextAction: "Resolve expired OEKO-TEX certificate",
    owner: "Imani Cole",
    updatedAt: "2 days ago",
    material: "54% wool, 44% recycled polyester, 2% elastane",
    recycledContent: 44,
    chain: compactChain("Forma", "Romania"),
  },
  {
    id: "OR-24021",
    name: "Nila Everyday Tee",
    sku: "NI-TS-014-WHT",
    category: "Jersey",
    season: "Core",
    color: "Optic white",
    completion: 89,
    status: "Needs evidence",
    suppliers: 3,
    evidence: 8,
    openItems: 2,
    nextAction: "Confirm care and repair instructions",
    owner: "Noah Williams",
    updatedAt: "3 days ago",
    material: "100% regenerative cotton",
    recycledContent: 0,
    chain: compactChain("Nila", "India"),
  },
  {
    id: "OR-24022",
    name: "Tera Storm Shell",
    sku: "TE-SH-901-MOS",
    category: "Outerwear",
    season: "AW 2026",
    color: "Alpine moss",
    completion: 100,
    status: "Passport ready",
    suppliers: 8,
    evidence: 24,
    openItems: 0,
    nextAction: "No action required",
    owner: "Maya Chen",
    updatedAt: "5 days ago",
    material: "100% recycled polyamide",
    recycledContent: 100,
    chain: compactChain("Tera", "Vietnam"),
  },
];

export const evidenceDocuments: EvidenceDocument[] = [
  {
    id: "DOC-1098",
    title: "GRS Transaction Certificate 24-9081",
    type: "Certification",
    supplier: "Luma Spinning",
    received: "Jul 15, 2026",
    confidence: 98,
    status: "Verified",
    fields: 12,
  },
  {
    id: "DOC-1097",
    title: "Fabric composition test — Batch NT-442",
    type: "Test report",
    supplier: "NovaTex Mill",
    received: "Jul 15, 2026",
    confidence: 96,
    status: "Verified",
    fields: 9,
  },
  {
    id: "DOC-1096",
    title: "Factory conformity declaration",
    type: "Supplier declaration",
    supplier: "Atelier Miro",
    received: "Jul 14, 2026",
    confidence: 91,
    status: "In review",
    fields: 15,
  },
  {
    id: "DOC-1095",
    title: "REACH dye-lot declaration",
    type: "Chemical compliance",
    supplier: "Chromia Works",
    received: "Not received",
    confidence: 0,
    status: "Missing",
    fields: 0,
  },
  {
    id: "DOC-1094",
    title: "FSC Chain of Custody — Packaging",
    type: "Certification",
    supplier: "Packwise Europe",
    received: "Jul 11, 2026",
    confidence: 99,
    status: "Verified",
    fields: 7,
  },
];

export const activity: ActivityEvent[] = [
  {
    title: "NovaTex uploaded a fabric test report",
    detail: "9 fields extracted · 96% confidence",
    time: "12 min",
    tone: "info",
  },
  {
    title: "Aster Loop Jacket moved to 84%",
    detail: "Material composition was verified",
    time: "31 min",
    tone: "success",
  },
  {
    title: "Chromia request is now overdue",
    detail: "REACH declaration · 2 days late",
    time: "2 hr",
    tone: "warning",
  },
];
