/**
 * Downloads the Latin subsets of the two site typefaces into `public/fonts/`
 * and writes the matching @font-face rules to `app/fonts.css`.
 *
 * next/font/google fetched every unicode subset Google offers (Cyrillic, Greek,
 * Vietnamese, ...) and preloaded all of them — around 370 kB before first
 * paint. The site renders English plus a few Latin-Extended characters, so only
 * `latin` and `latin-ext` are kept.
 *
 * Usage: node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontDir = join(root, "public/fonts");

// A modern desktop UA is required for Google to serve variable woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const KEEP = new Set(["latin", "latin-ext"]);

const families = [
  {
    cssVar: "--font-body",
    family: "Inter",
    slug: "inter",
    url: "https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap",
  },
  {
    cssVar: "--font-display",
    family: "Playfair Display",
    slug: "playfair-display",
    url: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400..900&display=swap",
  },
];

await mkdir(fontDir, { recursive: true });

const blocks = [];
const preloads = [];

for (const { family, slug, url } of families) {
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
    if (!r.ok) throw new Error(`${family}: ${r.status} ${r.statusText}`);
    return r.text();
  });

  // Google emits `/* subset */` immediately before each @font-face block.
  const faces = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!faces.length) throw new Error(`${family}: no @font-face blocks parsed`);

  for (const [, subset, face] of faces) {
    if (!KEEP.has(subset)) continue;

    const remote = face.match(/src:\s*url\(([^)]+)\)/)?.[1];
    if (!remote) throw new Error(`${family}/${subset}: no src url`);

    const file = `${slug}-${subset}.woff2`;
    const bytes = Buffer.from(
      await fetch(remote).then((r) => {
        if (!r.ok) throw new Error(`${file}: ${r.status}`);
        return r.arrayBuffer();
      }),
    );
    await writeFile(join(fontDir, file), bytes);
    console.log(`${file} -> ${(bytes.length / 1024).toFixed(1)} kB`);

    blocks.push(
      face
        .replace(/url\([^)]+\)/, `url("/fonts/${file}")`)
        .replace(/;\s*/g, ";\n  ")
        .replace(/@font-face\s*\{\s*/, `/* ${family} — ${subset} */\n@font-face {\n  `)
        .replace(/\s*\}$/, "\n}"),
    );

    // Only the primary Latin cut is worth preloading; latin-ext covers a
    // handful of supplier place names and can arrive with the swap.
    if (subset === "latin") preloads.push(`/fonts/${file}`);
  }
}

const out = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand. */

${blocks.join("\n\n")}

:root {
  --font-body: "Inter";
  --font-display: "Playfair Display";
}
`;

await writeFile(join(root, "app/fonts.css"), out);
console.log("\nwrote app/fonts.css");
console.log("preload:", preloads.join(", "));
